### ISSUE TITLE
Calendar event creation failed with error: insufficientPermissions after successful CR creation

### ISSUE THREAD

**Issue by himanshuGupta1391** [gojek/vision#17]
Steps to Reproduce:

- Create new CR by filling all mandatory fields
- Once CR is created, CR creation message will appear with error
<img width="1440" alt="Screenshot 2021-09-28 at 11 30 00 AM" src="https://user-images.githubusercontent.com/91447968/135071349-c0103fdd-a8a6-48bc-9b0c-fafefdd66935.png">

Result

- Google calendar is not created for deployment duration time

Expected result

- No error message should appear
- Google calendar event should be created

**Comment by r0r1** [comment]
could we mark it as done @himanshuGupta1391  ? resolved by manually adding list of users to GCalendar
