### ISSUE TITLE
Mandatory fields in Create CR & IR form is highlighted in Red

### ISSUE THREAD

**Issue by himanshuGupta1391** [gojek/vision#18]
Steps to reproduce:

- Click on New Change Request button
- On CR form, many mandatory fields like `Entity source`, `Change summary`, `Priority` etc are highlighted in red.
<img width="1308" alt="Screenshot 2021-09-28 at 10 16 40 AM" src="https://user-images.githubusercontent.com/91447968/135072086-b30a1e3f-3954-4220-8948-a6834fc08607.png">
<img width="1440" alt="Screenshot 2021-09-29 at 10 38 16 AM" src="https://user-images.githubusercontent.com/91447968/135206803-d3014027-a611-4c4e-a273-caad0950e7dd.png">

Expected Result:

- Mandatory fields should have asterisk (*) sign in red
<img width="1404" alt="Screenshot 2021-09-28 at 4 10 40 PM" src="https://user-images.githubusercontent.com/91447968/135072272-9b04b1b7-123d-466e-9f75-37bac0e63801.png">

**Comment by aangrayni** [comment]
@himanshuGupta1391 to verify again

**Comment by himanshuGupta1391** [comment]
Issue is still there in IR create form , I
![Uploading Screenshot 2021-10-01 at 3.35.05 PM.png…]()
t has been fixed in CR form only
