### ISSUE TITLE
No slack notification sent to the approver on creating CR

### ISSUE THREAD

**Issue by himanshuGupta1391** [gojek/vision#22]
Steps to Reproduce:
1. Create a valid CR with a valid approver
2. Slack notification of CR created will be sent
Sample CR: [https://vision-demo-app.herokuapp.com/change_requests/33](url)

Result:
1. No notification sent to approver's slack

Expected result:
1.Approver should get slack notification
2. Approver can approve/reject CR from slack itself

**Comment by rafeequl** [comment]
This is due missing config. Fixed on demo-app, @himanshuGupta1391 you can try it again

**Comment by rafeequl** [comment]
![image](https://user-images.githubusercontent.com/19315/135643103-95f0031b-33c7-48b1-9633-c46c11be63b8.png)

**Comment by rafeequl** [comment]
reopen for @himanshuGupta1391 to confirm

**Comment by himanshuGupta1391** [comment]
Slack notifications are coming on vision bot app. On current production, it appears on slackbot.
Should we maintain existing behaviour or send notification to vision bot? @rafeequl @barockok

**Comment by r0r1** [comment]
For CR app should be done right, for AR still figuring out

**Comment by himanshuGupta1391** [comment]
Slack notifications for AR are coming on different channels as per entity source selected
