### ISSUE TITLE
Change Request & Incident Report notification pages are empty

### ISSUE THREAD

**Issue by himanshuGupta1391** [gojek/vision#27]
<img width="1405" alt="Screenshot 2021-09-29 at 5 22 02 PM" src="https://user-images.githubusercontent.com/91447968/135267859-dcf03496-d6f5-456e-a814-cd95cc290878.png">

**Comment by rafeequl** [comment]
this caused by framework upgrade as well, the default behavior in Rails 5 is to expect `belongs_to`  to be mandatory.

**Comment by himanshuGupta1391** [comment]
Notification are coming now
<img width="1438" alt="Screenshot 2021-10-04 at 1 51 50 PM" src="https://user-images.githubusercontent.com/91447968/135817802-b448d65b-923f-4f69-9e65-8225ca96a17c.png">
<img width="1440" alt="Screenshot 2021-10-04 at 1 51 55 PM" src="https://user-images.githubusercontent.com/91447968/135817814-145ec794-5fc8-484a-9736-118bd31d0108.png">
