### ISSUE TITLE
Jira status is not showing in fields of Create CR form

### ISSUE THREAD

**Issue by himanshuGupta1391** [gojek/vision#29]
Steps to reproduce:
1. Go to create CR form
2. In business justification field, click on insert/edit link button
<img width="772" alt="Screenshot 2021-09-30 at 2 31 27 PM" src="https://user-images.githubusercontent.com/91447968/135422184-1b2b7d05-8710-4f5f-907a-48e880ac8cfc.png">
3. add Jira URL and ticket key
<img width="866" alt="Screenshot 2021-09-30 at 2 32 04 PM" src="https://user-images.githubusercontent.com/91447968/135422216-b9253924-ea24-423e-b9f5-fd8a4d8f5f8e.png">
4. Fill remaining fields and submit CR.
5. In CR detail, Jira status is not visible.
<img width="1440" alt="Screenshot 2021-09-30 at 1 42 15 PM" src="https://user-images.githubusercontent.com/91447968/135424266-f474bfe8-cccf-46dc-9db0-c6ac62f8c138.png">

Expected result:
Jira status should be shown
<img width="674" alt="Screenshot 2021-09-30 at 11 47 24 AM" src="https://user-images.githubusercontent.com/91447968/135424355-336c08e9-b0e2-49bc-a113-38ba6f38b619.png">

**Comment by r0r1** [comment]
please check again ya @himanshuGupta1391

**Comment by himanshuGupta1391** [comment]
`Definition of Success` & `Definition of Failure` these 2 fields should also show jira status as per internal gojek doc
<img width="1440" alt="Screenshot 2021-10-04 at 10 48 20 AM" src="https://user-images.githubusercontent.com/91447968/135804587-a01f78fa-783e-4d62-a950-3b49820405ab.png">
<img width="1440" alt="Screenshot 2021-10-04 at 10 48 34 AM" src="https://user-images.githubusercontent.com/91447968/135804599-7035da6f-2382-4a69-8ddf-183c4a894d62.png">

**Comment by himanshuGupta1391** [comment]
the above issue is on production as well
