### ISSUE TITLE
Mandatory fields in Create IR form is highlighted in Red

### ISSUE THREAD

**Issue by himanshuGupta1391** [gojek/vision#33]
Steps to reproduce:

- Click on New Incident Report button
- On IR form, many mandatory fields like Service impacted, source, rank etc are highlighted in red.
<img width="1440" alt="Screenshot 2021-10-01 at 3 35 05 PM" src="https://user-images.githubusercontent.com/91447968/135612804-f016f84d-8ef6-449c-8d45-f094221d33bc.png">

Expected Result:

- Mandatory fields should have asterisk (*) sign in red

**Comment by rafeequl** [comment]
this could be affected by rails upgrade

**Comment by himanshuGupta1391** [comment]
Not fixed yet
<img width="1440" alt="Screenshot 2021-10-04 at 9 56 00 AM" src="https://user-images.githubusercontent.com/91447968/135796273-bd09ff0e-5ab0-4f1e-877b-1af0074a98e5.png">

**Comment by himanshuGupta1391** [comment]
<img width="1176" alt="Screenshot 2021-10-04 at 12 01 57 PM" src="https://user-images.githubusercontent.com/91447968/135804654-490bcacb-24ec-4ede-97b2-6330f155803e.png">
All fields mentioned in this error message should be shown as mandatory in IR form

**Comment by r0r1** [comment]
@himanshuGupta1391 please check again ya, just deploy this to demo app
